---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aries-depl
  labels:
    app: aries-depl
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aries-depl
  template:
    metadata:
      labels:
        app: aries-depl
    spec:
      containers:
      - name: aries-depl
        image: klibio/io.klib.aries.example:develop-latest
        imagePullPolicy: IfNotPresent
        tty: true
        ports:
        - containerPort: 8080
          protocol: TCP
