apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-depl
  labels:
   app: aries-tut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aries-tut
  template:
    metadata:
      labels:
        app: aries-tut
    spec:
      containers:
      - name: aries-tut-container
        image: klibio/io.klib.aries.example:develop-latest
        imagePullPolicy: Always
        tty: true
        ports:
        - containerPort: 8080
          protocol: TCP
